bboard/bboard/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls', namespace='')),
]

if settings.DEBUG:
   urlpatterns.append(path('static/<path:path>', never_cache(serve)))

bboard/main/urls.py
from django.urls import path
from .views import index
from .views import other_page

app_name = 'main'

urlpatterns = [
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index')
]

bboard/main/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class AdvUser(AbstractUser):
    is_activated = models.BooleanField(default=True, db_index=True,
                                       verbose_name='Прошел активацию?')
    send_messages = models.BooleanField(default=True,
                                        verbose_name='Оповещать при новых комментариях?')

    class Meta(AbstractUser.Meta):
        pass


class TEST(models.Model):
    qwe = models.CharField(max_length=123)

bboard/main/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404
from django.template import TemplateDoesNotExist
from django.template.loader import get_template

# Create your views here.
def index(request):
   return render(request, 'main/index.html')

def other_page(request, page):
   try:
       template = get_template('main/' + page + '.html')
   except TemplateDoesNotExist:
       raise Http404
   return HttpResponse(template.render(request=request))

bboard/main/templates/layout/basic.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
{% bootstrap_css %}
{% bootstrap_javascript jquery='slim' %}
   <title>{% block title %} Главная {% endblock %} - Электронная доска объявлений </title>
</head>
<body>
<div class="container-fluid">
   <div class="d-flex flex-column flex-md-row p-3 px-md-4 mb-3  bg-white border-bottom box-shadow">
       <h5 class="mr-md-auto p-2">Электронная доска объявлений</h5>
       <div class="nav-item dropdown">
           <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Профиль</a>
           <div class="dropdown-menu">
               <a class="dropdown-item" href="#">Мои объявления</a>
               <a class="dropdown-item" href="#">Изменить личные данные</a>
               <a class="dropdown-item" href="#">Изменить пароль</a>
               <div class="dropdown-divider"></div>
               <a class="dropdown-item" href="#">Выйти</a>
               <div class="dropdown-divider"></div>
               <a class="dropdown-item" href="#">Удалить</a>
           </div>
       </div>
       <a class="p-2 text-dark" href="#">Регистрация</a>
       <a class="p-2 text-dark" href="#">Вход</a>
   </div>
   <div class="row">

       <nav class="col-md-auto nav flex-column">
           <a class="nav-link root" href="{% url 'main:index'  %}">Главная</a>
            <a class="nav-link root" href="{% url 'main:other' page='about' %}">О сайте</a>
           <span class="nav-link root font-weight-bold">
               Недвижимость
           </span>
           <a class="nav-link" href="#">Жилье</a>
           <a class="nav-link" href="#">Скалады</a>
           <a class="nav-link" href="#">Квартиры</a>

           <span class="nav-link root font-weight-bold">
               Транспорт
           </span>
           <a class="nav-link" href="#">Автомобили</a>
           <a class="nav-link" href="#">Мото</a>
           <a class="nav-link" href="#">Велосипеды</a>
       </nav>

       <div class="container">
       {% bootstrap_messages %}
       {% block content %}
       {% endblock %}
       </div>

   </div>

   <footer class="mt-3 border-top">
       <small class="p-2"> &copy; Методическое пособие: Знакомство с фреймворком
           Django. 2018-2019
       </small>
   </footer>
</div>

</body>
</html>

bboard/main/templates/main/about.html
{% extends "layout/basic.html" %}

{% block title %}О сайте{% endblock %}

{% block content %}
   <h2>О сайте</h2>
   <p>Этот сайт предназначен для публикации электронных объявлений</p>
   <p>Все права оформлены и охраняются законом РФ</p>
{% endblock %}

bboard/main/templates/main/index.html
{% extends "layout/basic.html" %}

{% block content %}

   <h2>Последние 10 объявлений</h2>
{% endblock %}